[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "10.8.0"
