-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "department_id" DROP NOT NULL,
ALTER COLUMN "position_id" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "join_date" SET DEFAULT CURRENT_TIMESTAMP;
